spring:
  application:
    name: auth-server
server:
  port: 9999
  forward-headers-strategy: framework

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://config-server:8888   
